import { useState } from 'react'
import html2canvas from 'html2canvas'
import { useApp } from '../context/AppContext'
import type { PinAssignment } from '../types/chip'

function generateArduinoDefines(chip: { name: string }, mapping: PinAssignment[]): string {
  if (mapping.length === 0) return '// No pins mapped yet'
  const lines = [
    `// Pin mapping for ${chip.name}`,
    `// Generated by ESP32 Pinout Studio`,
    '',
    ...mapping.map(a => `#define PIN_${a.label.toUpperCase().replace(/\s+/g, '_').replace(/[^A-Z0-9_]/g, '')} ${a.gpio}  // ${a.role}`),
  ]
  return lines.join('\n')
}

function drawWatermark(canvas: HTMLCanvasElement, scale: number) {
  const ctx = canvas.getContext('2d')
  if (!ctx) return
  const pad = 8 * scale
  ctx.font = `${11 * scale}px ui-monospace, SFMono-Regular, Menlo, monospace`
  ctx.textAlign = 'right'
  ctx.textBaseline = 'bottom'
  ctx.fillStyle = 'rgba(156, 163, 175, 0.85)'
  ctx.fillText('esp32pin.com', canvas.width - pad, canvas.height - pad)
}

export function ExportPanel() {
  const { chip, mapping, shareUrl, view } = useApp()
  const [copied, setCopied] = useState<'url' | 'code' | null>(null)

  const code = generateArduinoDefines(chip, mapping)

  const copyText = async (text: string, type: 'url' | 'code') => {
    await navigator.clipboard.writeText(text)
    setCopied(type)
    setTimeout(() => setCopied(null), 2000)
  }

  const download = (canvas: HTMLCanvasElement) => {
    const a = document.createElement('a')
    a.download = `${chip.id}-pinout.png`
    a.href = canvas.toDataURL('image/png')
    a.click()
  }

  const downloadPng = async () => {
    const scale = 2
    if (view === 'schematic') {
      // The schematic is a self-contained SVG sheet - rasterize it directly.
      // Full sheet regardless of zoom/scroll, no UI chrome, crisp at 2x, and
      // the sheet's own title block already carries the site credit.
      const svg = document.querySelector<SVGSVGElement>('#pinout-diagram-export svg')
      if (!svg) return
      const vb = svg.viewBox.baseVal
      const w = vb?.width || svg.clientWidth
      const h = vb?.height || svg.clientHeight
      const clone = svg.cloneNode(true) as SVGSVGElement
      clone.setAttribute('width', String(w))
      clone.setAttribute('height', String(h))
      const url = URL.createObjectURL(new Blob(
        [new XMLSerializer().serializeToString(clone)],
        { type: 'image/svg+xml;charset=utf-8' },
      ))
      try {
        const img = new Image()
        await new Promise<void>((res, rej) => {
          img.onload = () => res()
          img.onerror = () => rej(new Error('svg rasterize failed'))
          img.src = url
        })
        const canvas = document.createElement('canvas')
        canvas.width = w * scale
        canvas.height = h * scale
        const ctx = canvas.getContext('2d')!
        ctx.fillStyle = '#fdfcf6'
        ctx.fillRect(0, 0, canvas.width, canvas.height)
        ctx.scale(scale, scale)
        ctx.drawImage(img, 0, 0, w, h)
        download(canvas)
      } finally {
        URL.revokeObjectURL(url)
      }
      return
    }
    // Module view is HTML - capture the diagram content itself (full intrinsic
    // width, not the scroll-clipped card with its buttons and legend).
    const target = document.getElementById('module-diagram-canvas')
      ?? document.getElementById('pinout-diagram-export')
    if (!target) return
    const canvas = await html2canvas(target, { backgroundColor: '#060b12', scale })
    drawWatermark(canvas, scale)
    download(canvas)
  }

  const printPdf = () => {
    // A dedicated document tab the user can inspect, print or save as PDF.
    // The diagram is the live DOM plus the site's stylesheets - the browser
    // renders it natively (no html2canvas artifacts), scaled to fit A4.
    const w = window.open('', '_blank', 'width=920,height=760')
    if (!w) return
    const escapeHtml = (s: string) =>
      s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    const name = chip.module?.name ?? chip.name
    // A4 printable width at 96dpi with 12mm margins is ~700px.
    let diagramHtml = ''
    let moduleCss = ''
    if (view === 'schematic') {
      const svg = document.querySelector<SVGSVGElement>('#pinout-diagram-export svg')
      if (!svg) { w.close(); return }
      const clone = svg.cloneNode(true) as SVGSVGElement
      clone.removeAttribute('width')
      clone.removeAttribute('height')
      clone.setAttribute('style', 'width:100%;height:auto')
      diagramHtml = clone.outerHTML
    } else {
      const target = document.getElementById('module-diagram-canvas')
      if (!target) { w.close(); return }
      // Explicit measured dimensions + standard transform scale: Safari
      // mis-lays-out the zoom/fit-content shortcut.
      const mw = target.scrollWidth
      const mh = target.scrollHeight
      const scale = Math.min(1, 700 / mw)
      moduleCss = `
      .module-outer { width: ${Math.round(mw * scale)}px; height: ${Math.round(mh * scale)}px;
                      margin: 0 auto; overflow: hidden; }
      .module-print { width: ${mw}px; transform: scale(${scale}); transform-origin: top left; }`
      diagramHtml = `<div class="module-outer"><div class="module-print">${target.outerHTML}</div></div>`
    }
    // Carry the app's stylesheets over so the cloned module DOM renders 1:1.
    const styles = Array.from(document.querySelectorAll('style, link[rel="stylesheet"]'))
      .map(n => n.tagName === 'LINK'
        ? `<link rel="stylesheet" href="${(n as HTMLLinkElement).href}">`
        : `<style>${n.textContent}</style>`)
      .join('\n')
    const gotchas = chip.notes.map(n => `<li>${escapeHtml(n)}</li>`).join('')
    const rows = mapping.map(a =>
      `<tr><td>GPIO${a.gpio}</td><td>${escapeHtml(a.role)}</td><td>${escapeHtml(a.label)}</td></tr>`).join('')
    w.document.write(`<!doctype html><html><head><title>${escapeHtml(name)} pinout</title>
    ${styles}
    <style>
      @page { size: A4; margin: 12mm; }
      html, body { all: revert; height: auto; }
      * { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      body { font: 12px/1.45 -apple-system, "Segoe UI", sans-serif; color: #111; margin: 0; background: #fff; }
      main { max-width: 760px; margin: 0 auto; padding: 16px; }
      h1 { font-size: 20px; margin: 0 0 2px; }
      .sub { color: #555; margin: 0 0 10px; font-size: 11px; }
      svg { max-width: 100%; height: auto; display: block; }
      /* Paper is white - the module sits directly on it, no dark app card. */${moduleCss}
      @media print { main { padding: 0; max-width: none; } .foot { margin-bottom: 0; } }
      h2 { font-size: 13px; margin: 12px 0 4px; }
      ul.gotchas { margin: 0; padding-left: 18px; list-style: disc; }
      ul.gotchas li { margin: 2px 0; }
      table.map { border-collapse: collapse; margin-top: 4px; font-size: 11px; }
      table.map td, table.map th { border: 1px solid #bbb; padding: 3px 8px; text-align: left; }
      .foot { margin-top: 10px; color: #555; font-size: 10px; }
      .toolbar { text-align: right; margin: 0 0 10px; }
      .toolbar button { font: 600 13px -apple-system, "Segoe UI", sans-serif; padding: 7px 16px;
                        border-radius: 7px; border: 1px solid #ccc; background: #1d4ed8; color: #fff; cursor: pointer; }
      @media print { .toolbar { display: none; } }
    </style></head><body>
    <main>
      <div class="toolbar"><button onclick="window.print()">Print / Save as PDF</button></div>
      <h1>${escapeHtml(name)} pinout</h1>
      <p class="sub">ESP32 Pinout Studio - esp32pin.com/${chip.id} - ${new Date().toISOString().slice(0, 10)}</p>
      ${diagramHtml}
      <h2>Known gotchas</h2><ul class="gotchas">${gotchas}</ul>
      ${rows ? `<h2>Pin mapping</h2><table class="map"><tr><th>GPIO</th><th>Role</th><th>Label</th></tr>${rows}</table>` : ''}
      <p class="foot">Interactive version with live conflict checking: https://esp32pin.com/${chip.id}</p>
    </main>
    </body></html>`)
    w.document.close()
  }

  return (
    <div className="space-y-4">
      <h2 className="text-sm font-semibold text-gray-300">Export</h2>

      {/* Shareable URL */}
      <div>
        <label className="text-xs text-gray-500 block mb-1">Shareable URL</label>
        <div className="flex gap-2">
          <input
            readOnly
            value={shareUrl}
            className="flex-1 bg-gray-800 border border-gray-700 rounded px-2 py-1.5 text-xs text-gray-300 font-mono overflow-hidden"
          />
          <button
            onClick={() => copyText(shareUrl, 'url')}
            className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-xs text-gray-200 whitespace-nowrap transition-colors"
          >
            {copied === 'url' ? '✓ Copied' : 'Copy'}
          </button>
        </div>
      </div>

      {/* Arduino #defines */}
      <div>
        <label className="text-xs text-gray-500 block mb-1">Arduino / PlatformIO</label>
        <pre className="bg-gray-800 border border-gray-700 rounded p-3 text-xs font-mono text-green-400 overflow-x-auto whitespace-pre max-h-48">
          {code}
        </pre>
        <button
          onClick={() => copyText(code, 'code')}
          className="mt-2 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-xs text-gray-200 transition-colors"
        >
          {copied === 'code' ? '✓ Copied' : 'Copy code'}
        </button>
      </div>

      {/* PNG Download */}
      <div>
        <button
          onClick={downloadPng}
          className="w-full px-3 py-2 bg-blue-800 hover:bg-blue-700 rounded text-sm text-white font-medium transition-colors"
        >
          ⬇ Download Pinout PNG
        </button>
        <button
          onClick={printPdf}
          className="w-full mt-2 px-3 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 rounded text-sm text-gray-200 font-medium transition-colors"
        >
          🖨 Print / Save as PDF
        </button>
        <p className="text-xs text-gray-600 mt-1">PNG captures the diagram; PDF makes an A4 cheat sheet with the gotcha list.</p>
      </div>
    </div>
  )
}
