import { useState } from 'react'
import html2canvas from 'html2canvas'
import { useApp } from '../context/AppContext'
import type { PinAssignment } from '../types/chip'

function generateArduinoDefines(chip: { name: string }, mapping: PinAssignment[]): string {
  if (mapping.length === 0) return '// No pins mapped yet'
  const lines = [
    `// Pin mapping for ${chip.name}`,
    `// Generated by ESP32 Pinout Studio`,
    '',
    ...mapping.map(a => `#define PIN_${a.label.toUpperCase().replace(/\s+/g, '_').replace(/[^A-Z0-9_]/g, '')} ${a.gpio}  // ${a.role}`),
  ]
  return lines.join('\n')
}

export function ExportPanel() {
  const { chip, mapping, shareUrl } = useApp()
  const [copied, setCopied] = useState<'url' | 'code' | null>(null)

  const code = generateArduinoDefines(chip, mapping)

  const copyText = async (text: string, type: 'url' | 'code') => {
    await navigator.clipboard.writeText(text)
    setCopied(type)
    setTimeout(() => setCopied(null), 2000)
  }

  const downloadPng = async () => {
    const target = document.getElementById('pinout-diagram-export')
    if (!target) return
    const canvas = await html2canvas(target, { backgroundColor: '#030712', scale: 2 })
    const a = document.createElement('a')
    a.download = `${chip.id}-pinout-mapping.png`
    a.href = canvas.toDataURL('image/png')
    a.click()
  }

  return (
    <div className="space-y-4">
      <h2 className="text-sm font-semibold text-gray-300">Export</h2>

      {/* Shareable URL */}
      <div>
        <label className="text-xs text-gray-500 block mb-1">Shareable URL</label>
        <div className="flex gap-2">
          <input
            readOnly
            value={shareUrl}
            className="flex-1 bg-gray-800 border border-gray-700 rounded px-2 py-1.5 text-xs text-gray-300 font-mono overflow-hidden"
          />
          <button
            onClick={() => copyText(shareUrl, 'url')}
            className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-xs text-gray-200 whitespace-nowrap transition-colors"
          >
            {copied === 'url' ? '✓ Copied' : 'Copy'}
          </button>
        </div>
      </div>

      {/* Arduino #defines */}
      <div>
        <label className="text-xs text-gray-500 block mb-1">Arduino / PlatformIO</label>
        <pre className="bg-gray-800 border border-gray-700 rounded p-3 text-xs font-mono text-green-400 overflow-x-auto whitespace-pre max-h-48">
          {code}
        </pre>
        <button
          onClick={() => copyText(code, 'code')}
          className="mt-2 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-xs text-gray-200 transition-colors"
        >
          {copied === 'code' ? '✓ Copied' : 'Copy code'}
        </button>
      </div>

      {/* PNG Download */}
      <div>
        <button
          onClick={downloadPng}
          className="w-full px-3 py-2 bg-blue-800 hover:bg-blue-700 rounded text-sm text-white font-medium transition-colors"
        >
          ⬇ Download Pinout PNG
        </button>
        <p className="text-xs text-gray-600 mt-1">Captures the diagram including your mapping labels.</p>
      </div>
    </div>
  )
}
